version: '3.8'

services:
  frontend:
    image: chatendimento/frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_URL=http://backend:3000

  backend:
    image: chatendimento/backend:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped